services:
  alphavantage.marketpull.daily:
    image: alphavantage-marketpull-daily:prod
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - INTERVAL_TYPE=OneDay
      - CRON_SCHEDULE=0 18 * * 1-5
      - TZ=America/New_York
    volumes:
      - shared-storage:/app/sharedstorage
    networks:
      - shared-network

  alphavantage.marketpull.weekly:
    image: alphavantage-marketpull-weekly:prod
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - INTERVAL_TYPE=OneWeek
      - CRON_SCHEDULE=0 3 * * 1
      - TZ=America/New_York
    volumes:
      - shared-storage:/app/sharedstorage
    networks:
      - shared-network

volumes:
  shared-storage:

networks:
  shared-network: